export type ModelProvider =
  | "openai"
  | "google"
  | "anthropic"
  | "mistral"
  | "groq"
  | "perplexity"
  | "ollama"
  | "openrouter"
  | "custom"
  | "pollination"
  | "blackbox"
  | "aryahcr"
  | "ails"
  | "zanity"
  | "airforce"
